<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE digidex [
<!ELEMENT digidex (digimon+)>
<!ELEMENT digimon (name, type, level, abilities, baseStats, legendary?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT level (#PCDATA)>
<!ELEMENT abilities (ability+)>
<!ELEMENT ability (#PCDATA)>
<!ELEMENT baseStats (HP, ATK, DEF)>
<!ELEMENT HP (#PCDATA)>
<!ELEMENT ATK (#PCDATA)>
<!ELEMENT DEF (#PCDATA)>
<!ELEMENT legendary EMPTY>
]>

<digidex>

    <digimon>
        <name>Agumon</name>
        <type>fuego</type>
        <level>60</level>
        <abilities>
            <ability>Pepper Breath</ability>
        </abilities>
        <baseStats>
            <HP>1000</HP>
            <ATK>1000</ATK>
            <DEF>1000</DEF>
        </baseStats>
        <legendary />
    </digimon>

    <digimon>
        <name>Gabumon</name>
        <type>energia</type>
        <level>50</level>
        <abilities>
            <ability>Blue Blaster</ability>
            <ability>Petit Fire</ability>
        </abilities>
        <baseStats>
            <HP>1000</HP>
            <ATK>1000</ATK>
            <DEF>1000</DEF>
        </baseStats>
    </digimon>

</digidex>
