=== Victoria-STEM/Bases_de_Datos/GitHub/Lenguaje_de_Marca/UD_1/repaso/digidex.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema-instance">
    <xs:element name="digidex">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="digimon" minOccurs="2" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="type">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Virus"/>
                                        <xs:enumeration value="Vaccine"/>
                                        <xs:enumeration value="Data"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="level"> 
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Rookie"/>
                                        <xs:enumeration value="Champion"/>
                                        <xs:enumeration value="Ultimate"/>
                                        <xs:enumeration value="Mega"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="abilities">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ability" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="baseStats">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="HP">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:interger">
                                                    <xs:minExclusive value="1"/>
                                                    <xs:maxExclusive value="999"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="ATK">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:minExclusive value="1"/>
                                                    <xs:maxExclusive value="500"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="DEF">
                                            <xs:simpleType> 
                                                <xs:restriction base="xs:integer">
                                                    <xs:minExclusive value="1"/>
                                                    <xs:maxExclusive value="400"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name= "legendary" type="xs:string" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Victoria-STEM/Bases_de_Datos/GitHub/Lenguaje_de_Marca/UD_1/repaso/digidex-2.xml
<?xml version="1.0" encoding="UTF-8"?>

<digidex xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="digidex.xsd">
    
    <digimon>
        <name>Agumon</name>
        <type>fuego</type>
        <level>60</level>
        <abilities>
            <ability>Pepper Breath</ability>
        </abilities>
        <baseStats>
            <HP>1000</HP>
            <ATK>1000</ATK>
            <DEF>1000</DEF>
        </baseStats>
        <legendary />
    </digimon>

    <digimon>
        <name>Gabumon</name>
        <type>energia</type>
        <level>50</level>
        <abilities>
            <ability>Blue Blaster</ability>
            <ability>Petit Fire</ability>
        </abilities>
        <baseStats>
            <HP>1000</HP>
            <ATK>1000</ATK>
            <DEF>1000</DEF>
        </baseStats>
    </digimon>

</digidex>
