<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Carta [
    <!ELEMENT Carta (plato+)>
    <!ELEMENT plato (nombre, descripcion, alergenos?, ingredientes+)>
    <!ELEMENT alergenos (alergeno*)>
    <!ELEMENT ingredientes (ingrediente*)>
    <!ELEMENT ingrediente (nombreIngrediente, cantidad, unidadMedida)>

    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT descripcion (#PCDATA)>
    <!ELEMENT alergeno (#PCDATA)>
    <!ELEMENT nombreIngrediente (#PCDATA)>
    <!ELEMENT cantidad (#PCDATA)>
    <!ELEMENT unidadMedida (#PCDATA)>

    <!ATTLIST plato tipo CDATA #IMPLIED>
]>

<Carta>

    <plato>
        <nombre>Lasanha</nombre>
        <descripcion>Sabrosisimas capas de pasta rellena</descripcion>
        <alergenos>
            <alergeno>Huevo</alergeno>
            <alergeno></alergeno>
        </alergenos>
        <ingredientes>
            <ingrediente>
                <nombreIngrediente>tomate</nombreIngrediente>
                <cantidad>2</cantidad>
                <unidadMedida>100g</unidadMedida>
            </ingrediente>
            <ingrediente>
                <nombreIngrediente>pasta</nombreIngrediente>
                <cantidad>3</cantidad>
                <unidadMedida>200g</unidadMedida>
            </ingrediente>
        </ingredientes>
    </plato>

    <plato tipo="vegetariano">
        <nombre>Huevo frito</nombre>
        <descripcion>Huevo de gallina campera frito en aceite de oliva.</descripcion>
        <alergenos>
            <alergeno>Huevo</alergeno>
            <alergeno></alergeno>
        </alergenos>
        <ingredientes>
            <ingrediente>
                <nombreIngrediente>Huevo campero</nombreIngrediente>
                <cantidad>1</cantidad>
                <unidadMedida>100g</unidadMedida>
            </ingrediente>
        </ingredientes>
    </plato>

</Carta>