<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE persona [
    <!ELEMENT persona (nombre, edad, direccion)>
    <!ELEMENT direccion (calle, codigoPostal, poblacion)>

    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT edad (#PCDATA)>
    <!ELEMENT calle (#PCDATA)> 
    <!ELEMENT codigoPostal (#PCDATA)>
    <!ELEMENT poblacion (#PCDATA)>  
    
    <!ATTLIST poblacion tipo CDATA #REQUIRED>
]>

<persona>
    <nombre>Marcos</nombre>
    <edad>18</edad>
    <direccion>
        <calle>Boqueron</calle>
        <codigoPostal>18001</codigoPostal>
        <poblacion tipo="ciudad">Granada</poblacion>
    </direccion>
</persona>